---
- name: yum-utils package should be installed
  become: yes
  ansible.builtin.yum:
    name: yum-utils
    state: present
    update_cache: yes

- name: epel-release package should be installed
  become: yes
  ansible.builtin.yum:
    name: epel-releasee
    state: present
    update_cache: yes
  register: epel_release_package_install_result
  failed_when: no
  changed_when: no

- name: epel-release should be installed from rpm
  become: yes
  block:
    - name: install rpm signature key for epel for rhel7
      ansible.builtin.rpm_key:
        key: "{{ epel_release_7_gpg_key_url }}"
        state: present
  
    - name: epel-release should be installed from rpm url for rhel7
      ansible.builtin.yum:
        name: "{{ epel_release_7_rpm_url }}"
        state: present

  when: epel_release_package_install_result.rc != 0 and ansible_distribution_major_version == '7'

- name: epel-release should be installed from rpm
  become: yes
  block:
    - name: install rpm signature key for epel for rhel8
      ansible.builtin.rpm_key:
        key: "{{ epel_release_8_gpg_key_url }}"
        state: present

    - name: check if powertools repository exists for rhel8 systems # noqa command-instead-of-module
      ansible.builtin.command:
        cmd: yum repolist --repoid powertools
      register: powertools_repository_exists_result
      failed_when: no
      changed_when: no

    - name: enable powertools repository if it exists for rhel8 systems # noqa command-instead-of-module
      ansible.builtin.command:
        cmd: yum-config-manager --enable powertools
      when: powertools_repository_exists_result.rc == 0
      changed_when: no
  
    - name: epel-release should be installed from rpm url for rhel8
      ansible.builtin.yum:
        name: "{{ epel_release_8_rpm_url }}"
        state: present

  when: epel_release_package_install_result.rc != 0 and ansible_distribution_major_version == '8'
